package:
  name: distance_heatmap
  version: 0.0.1

source:
#  git_rev: https://github.com/simonholmes001/distance_heatmap/releases/tag/v0.0.1
  git_url: https://github.com/simonholmes001/distance_heatmap.git

build:
  number: 1

requirements:
  build:
    - python=3.7.7
  run:
    - python=3.7.7
    - pandas
    - matplotlib
    - seaborn
    - numpy

test:
  imports:
    -

about:
  home:
  license: BSD
  license_family: BSD
  summary: Creates a distance heatmap from a distance or adjacency matrix